Repository TooNovel/TooNovel-FE, pull requests merged in 2023-06, with the labels that each got.

#43 [STYLE] 소셜 로그인 버튼 개선
  public/TooNovel_logo_light.png
  public/google_login.png
  public/kakao_login_large_wide.png
  src/views/LoginPage.vue
Labels: :art: Style

#42 [FEAT] 커뮤니티, 작가 페이지 구현
  src/components/PostLike.vue
  src/components/layout/MainHeader.vue
  src/router/index.js
  src/views/CommunityPage.vue
  src/views/FanclubPage.vue
  src/views/PostDetailPage.vue
  src/views/PostWritePage.vue
Labels: :recycle: refactor, :sparkles: Feature

#46 [BUG] [REFACTOR] api 통신 테스트 및 새로 고침 시 데이터 초기화 되는 버그 현상
  src/components/MyPageHeader.vue
  src/components/NovelLike.vue
  src/components/layout/MainHeader.vue
  src/router/index.js
  src/style/loader.css
  src/style/novel-detail.css
  src/views/MainPage.vue
  src/views/MyLikeNovel.vue
  src/views/MyPage.vue
  src/views/MyReview.vue
  src/views/NovelDetailPage.vue
  src/views/NovelViewPage.vue
  src/views/ReviewTotalPage.vue
Labels: :bug: Bug, :recycle: refactor

#50 [FEAT] 관리자 페이지 구현
  src/components/MyPageNavbar.vue
  src/router/index.js
  src/views/AdminAuthorPage.vue
  src/views/AdminUserPage.vue
Labels: :sparkles: Feature

#53 [REFACTOR] 토큰 전달 리팩토링
  src/components/PostLike.vue
  src/components/layout/MainHeader.vue
  src/views/AuthorNovelPage.vue
  src/views/CommunityPage.vue
  src/views/JoinPage.vue
  src/views/MyLikeNovel.vue
  src/views/MyReview.vue
  src/views/NovelDetailPage.vue
  src/views/PostDetailPage.vue
  src/views/PostWritePage.vue
  src/views/RecommendPage.vue
  src/views/UserLikeNovelPage.vue
Labels: :recycle: refactor

#56 [FEAT] 웹소설 신청 페이지 추가 , 추천 페이지 수정
  src/components/layout/MainHeader.vue
  src/router/index.js
  src/views/NovelRequestPage.vue
  src/views/RecommendPage.vue
Labels: :recycle: refactor, :sparkles: Feature

#58 [FEAT] API 연결 추가 , 신청페이지 이동 구현
  src/components/layout/MainHeader.vue
  src/views/FanclubPage.vue
  src/views/MainPage.vue
  src/views/NovelDetailPage.vue
  src/views/NovelSearchPage.vue
Labels: :recycle: refactor, :sparkles: Feature

#59 [FEAT] 마이페이지 프로필 수정 기능 구현
  src/views/JoinPage.vue
  src/views/MyPage.vue
Labels: :sparkles: Feature

#69 [REFACTOR] 게시글, 추천, 작품 페이지 수정
  src/views/CommunityPage.vue
  src/views/FanclubPage.vue
  src/views/NovelSearchPage.vue
  src/views/NovelViewPage.vue
  src/views/PostWritePage.vue
  src/views/RankingPage.vue
  src/views/RecommendPage.vue
Labels: :recycle: refactor

#71 [FEAT] 관리자 페이지 구현
  src/components/MyPageNavbar.vue
  src/router/index.js
  src/views/AdminAuthorPage.vue
  src/views/AdminModelUpdatePage.vue
  src/views/AdminPage.vue
Labels: :recycle: refactor, :sparkles: Feature

#73 [STYLE] 이미지 크기 조정
  src/views/MainPage.vue
  src/views/NovelDetailPage.vue
  src/views/ReviewTotalPage.vue
Labels: :art: Style

#77 [FEAT] 메신저 기능
  package-lock.json
  package.json
  src/App.vue
  src/main.js
  src/router/index.js
  src/style/button.css
  src/style/chat.css
  src/views/ChatRoom.vue
  src/views/ChatWindow.vue
  src/views/FanclubPage.vue
  src/views/MyChatRoom.vue
  src/views/MyFollowChat.vue
  src/views/NovelDetailPage.vue
Labels: :sparkles: Feature, :art: Style

#80 [STYLE] 리뷰 이미지 수정
  src/views/ReviewTotalPage.vue
Labels: :art: Style

#81 [BUG] 소설 상세 조회 페이지 로딩바
  src/views/NovelDetailPage.vue
Labels: :bug: Bug, :recycle: refactor

#82 [BUG] 소설 전체 조회 페이지 로딩바 수정
  src/views/NovelViewPage.vue
Labels: :bug: Bug

#87 [BUG] 작가 검색 버그
  src/views/FanclubPage.vue
Labels: :bug: Bug, :recycle: refactor

#89 [BUG] 채팅방 관련 다수의 버그
  src/views/ChatWindow.vue
Labels: :bug: Bug

#90 [REFACTOR]통계 페이지 리팩터링
  src/views/AdminPage.vue
  src/views/NovelStatisticsPage.vue
Labels: :recycle: refactor

#93 [REFACTOR] 채팅방 참여 오류 처리, 작가 이미지 틀 수정
  src/style/button.css
  src/views/FanclubPage.vue
  src/views/MainPage.vue
Labels: :recycle: refactor, :art: Style

#95 [STYLE] 메인페이지 캐러셀 일부 수정
  src/components/NovelLike.vue
  src/components/PostLike.vue
  src/style/novel-detail.css
  src/views/FanclubPage.vue
  src/views/MainPage.vue
  src/views/NovelDetailPage.vue
Labels: :art: Style

#98 [STYLE]관리자 통계 페이지 css 수정
  src/components/MyPageNavbar.vue
  src/views/AdminPage.vue
  src/views/MainPage.vue
  src/views/MyPage.vue
Labels: :art: Style

#102 [STYLE] 작품 상세 조회 CSS
  package-lock.json
  package.json
  src/main.js
  src/views/NovelDetailPage.vue
Labels: :art: Style

#105 [STYLE] 팬클럽 페이지, 푸터 수정
  src/components/layout/MainFooter.vue
  src/views/FanclubPage.vue
  src/views/MainPage.vue
Labels: :art: Style

#108 [REFACTOR] input에 enter 이벤트 적용
  src/components/layout/MainHeader.vue
  src/views/ChatWindow.vue
  src/views/FanclubPage.vue
  src/views/NovelSearchPage.vue
Labels: :recycle: refactor, :sparkles: Feature

#110 [STYLE]작가 통계 페이지 css 작업
  src/views/AdminPage.vue
  src/views/AuthorNovelPage.vue
  src/views/NovelStatisticsPage.vue
Labels: :art: Style

#112 [STYLE] 통계 페이지 일부 개선
  package-lock.json
  package.json
  src/views/NovelStatisticsPage.vue
Labels: :bug: Bug, :art: Style

#113 [BUG]마이페이지 일부 수정
  src/views/MyPage.vue
Labels: :bug: Bug

#114 [STYLE] 소설 전체 조회 CSS
  src/views/NovelViewPage.vue
Labels: :art: Style

#116 [REFACTOR] 리뷰 페이지 변경
  src/views/FanclubPage.vue
  src/views/MainPage.vue
  src/views/MyReview.vue
  src/views/ReviewTotalPage.vue
Labels: :recycle: refactor

#118 [FEAT] 필터링된 메세지에 대한 답장 경고
  src/store/store.js
  src/views/ChatWindow.vue
  src/views/MyChatRoom.vue
  src/views/MyFollowChat.vue
Labels: :bug: Bug, :sparkles: Feature

#122 [BUG] 관리자 통계 페이지 통계 제목 버그
  src/views/AdminPage.vue
  src/views/NovelStatisticsPage.vue
Labels: :bug: Bug

#125 [STYLE] 간단한 디자인 수정
  public/favicon.ico
  public/index.html
  public/robot.gif
  src/style/chat.css
  src/views/MainPage.vue
  src/views/NovelDetailPage.vue
  src/views/NovelSearchPage.vue
  src/views/NovelViewPage.vue
  src/views/RecommendPage.vue
Labels: :art: Style

#123 [FEAT] 채팅방 탈퇴 기능
  src/views/ChatRoom.vue
  src/views/MyChatRoom.vue
  src/views/MyFollowChat.vue
Labels: :sparkles: Feature

#127 [STYLE] 리뷰 페이지 변경
  src/views/MyReview.vue
  src/views/ReviewTotalPage.vue
Labels: :art: Style

#129 [BUG] 추천 페이지 로딩 버그
  src/views/RecommendPage.vue
Labels: :bug: Bug, :art: Style

#130 [BUG] 전체 소설 조회 페이지 버그 수정
  src/views/NovelViewPage.vue
Labels: :bug: Bug

#132 [REFACTOR] 소설 제목 출력 형식 수정
  src/views/NovelViewPage.vue
Labels: :recycle: refactor

#134 [STYLE] 랭킹 페이지 CSS
  src/components/RankingNavbar.vue
  src/views/RankingPage.vue
Labels: :art: Style

#136 [STYLE] 메인, 리뷰, 검색 페이지 수정
  src/views/MainPage.vue
  src/views/NovelSearchPage.vue
  src/views/ReviewTotalPage.vue
Labels: :art: Style

#138 [STYLE] 헤더 버튼 CSS
  src/components/layout/MainHeader.vue
Labels: :art: Style
