Repository TooNovel/TooNovel-FE, pull requests merged in 2023-05, with the labels that each got.

#11 [FEAT] Review 조회 페이지 일부 구현
  src/components/layout/MainHeader.vue
  src/router/index.js
  src/views/ReviewTotalPage.vue
Labels: :sparkles: Feature

#15 [FEAT] store 구현
  src/components/layout/MainHeader.vue
  src/store/store.js
  src/views/JoinPage.vue
  vue.config.js
Labels: :sparkles: Feature

#17 [BUG] store 액세스 토큰 저장 버그 발생
  src/components/layout/MainHeader.vue
  src/views/JoinPage.vue
Labels: :bug: Bug

#18 추천 페이지 제작
  src/components/layout/MainHeader.vue
  src/router/index.js
  src/views/MainPage.vue
  src/views/RecommendPage.vue
Labels: :sparkles: Feature, :art: Style

#20 [FEAT] 작품 상세 페이지 리뷰 기능 구현
  src/views/NovelDetailPage.vue
  src/views/RecommendPage.vue
Labels: :sparkles: Feature, :art: Style

#21 디자인 지나치게 부족한 부분 수정
  src/views/MainPage.vue
  src/views/NovelViewPage.vue
  src/views/RecommendPage.vue
  src/views/ReviewTotalPage.vue
Labels: :bug: Bug, :art: Style

#23 [FEAT] 좋아요 한 작품 조회 기능
  src/router/index.js
  src/views/NovelViewPage.vue
  src/views/UserLikeNovelPage.vue
Labels: :sparkles: Feature

#24 [FEAT] 작품 검색 기능 구현
  src/components/layout/MainHeader.vue
  src/router/index.js
  src/views/NovelSearchPage.vue
  src/views/NovelViewPage.vue
Labels: :sparkles: Feature

#25 [STYLE] 좋아요 버튼 디자인 제작
  src/views/NovelDetailPage.vue
Labels: :art: Style

#28 Yju kim jeong su/issue27
  src/components/layout/MainHeader.vue
  src/views/JoinPage.vue
  src/views/MainPage.vue
  src/views/NovelDetailPage.vue
  src/views/NovelSearchPage.vue
  src/views/NovelViewPage.vue
  src/views/PostWritePage.vue
  src/views/RecommendPage.vue
  src/views/ReviewTotalPage.vue
  src/views/UserLikeNovelPage.vue
  src/views/WorkViewPage.vue
Labels: :recycle: refactor

#30 [FEAT] 좋아요 기능 구현
  public/TooNovel-logo.png
  src/components/NovelLike.vue
  src/components/layout/MainHeader.vue
  src/style/novel-detail.css
  src/views/MainPage.vue
  src/views/NovelDetailPage.vue
Labels: :sparkles: Feature

#36 [REFACTOR] 소셜 로그인 redirect_uri 리팩토링
  src/views/LoginPage.vue
Labels: :recycle: refactor

#38 [BUG] 작품 검색 버그 발생 및 리팩토링
  src/components/layout/MainHeader.vue
  src/views/NovelSearchPage.vue
Labels: :bug: Bug, :recycle: refactor

#41 :bug: vue 의존성이 삭제된 문제 수정
  package-lock.json
  package.json
Labels: :bug: Bug
